bump(main/sc-im): 0.8.4
* Use LUA_PKGNAME to select lua version instead of patching makefile.
  That option for make was added in the following upstream commit
  https://github.com/andmarti1424/sc-im/commit/5c2e0a19e26a99e899751f72f9715fd35f3131eb

* Update lua dependency to lua5.4.

* Fix the following compiler error with interp.c and modified langinfo.h.
  langinfo.h:107:1: error: function definition is not allowed here