fix(main/libxml2): add missing `python` build dependency in case package needs to be built without `libxml2-python.subpackage`
```
[termux_setup_python_pip]: Applying python-crossenv-PYTHONPATH.patch
ERROR: /data/data/com.termux/files/usr/bin/python3.11 does not exist
```