fix(main/python): add missing `tk` build dependency in case package needs to be built without `python-tkinter.subpackage`
```
ERROR: Python module library _tkinter not built
```